// Generated by dts-bundle-generator v8.0.0

import { Component, h, render } from 'preact';
import { useEffect, useRef, useState } from 'preact/hooks';

declare namespace __preact {
	export { useState };
	export { useEffect };
	export { useRef };
	export { Component };
	export { render };
	export namespace React {
		export { h as createElement };
	}
}

export {};
